server {
    server_name mtsn1pandeglang.sch.id www.mtsn1pandeglang.sch.id;
    root /var/www/mtsn1pandeglang.sch.id/dist;
    index index.html index.htm index.php;
    access_log off; 
    error_log /var/log/nginx/mtsn1pandeglang.error.log warn;
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types 
        text/plain 
        text/css 
        application/json 
        application/javascript 
        text/xml 
        application/xml 
        application/xml+rss 
        text/javascript 
        image/svg+xml 
        application/vnd.ms-fontobject 
        application/x-font-ttf 
        font/opentype;
    open_file_cache max=10000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff|woff2|ttf)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public, no-transform";
    }
    location ~* \.(?:css|js)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public, no-transform";
    }
    location ~* \.(?:html|json|xml)$ {
        expires 1y;
        add_header Cache-Control "public, must-revalidate";
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock; 
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
    location ~ /\. {
        deny all;
      	return 404;
    }
    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/mtsn1pandeglang.sch.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mtsn1pandeglang.sch.id/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = www.mtsn1pandeglang.sch.id) {
        return 301 https://$host$request_uri;
    }
    if ($host = mtsn1pandeglang.sch.id) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    listen [::]:80;
    server_name mtsn1pandeglang.sch.id www.mtsn1pandeglang.sch.id;
    return 404;
}
